### ISSUE TITLE
Windows 10 issue with Parameters lesson

### ISSUE THREAD

**Issue by NickParks** [denysdovhan/learnyoubash#4] opened 2016-02-17 02:22 UTC
Hello, so I was going along with the lessons fairly smoothly until I got to the Parameters lesson to print out the first, third, and fifth parameter.

I've tried multiple methods but below is just an example of one
`#!/usr/env/bin bash
echo "1: $1"
echo "3: $3"
echo "5: $5"`

The result in the cygwin window is below:
![image](https://cloud.githubusercontent.com/assets/5506537/13097871/d0b61c8a-d4d9-11e5-8231-45168f23e748.png)

Is there something i'm doing wrong or is this an actual issue?

**Comment by denysdovhan** [comment] 2016-02-17 05:49
I'll try to reproduce it on

**Comment by denysdovhan** [comment] 2016-02-17 05:51
Sorry, I'm not home and my phone hates me :)

I'll try to reproduce the bug on my Windows environment as soon as I get home. Thank you for feedback!

**Comment by denysdovhan** [comment] 2016-02-17 12:53
Yep, there is something wrong with it.

You can use **git bash** until it will be fixed. It works well there.

**Comment by denysdovhan** [comment] 2016-02-17 13:03
What the versions of Cygwin and Bash are you using? 

I guess the problem is in https://github.com/nodejs/node/issues/3006.

**Comment by NickParks** [comment] 2016-02-18 02:10
Cygwin - 2.4.1
Bash - 4.3.42(4)

**Comment by denysdovhan** [comment] 2017-03-21 08:19
@SirNickParks hi! could you, please, check with the latest version of `learnyoubash`?

**Comment by denysdovhan** [comment] 2017-12-25 22:23
Closing this as @SirNickParks not responding.

**Closed as completed by denysdovhan** 2017-12-25 22:23 UTC
Labels: bug
