### ISSUE TITLE
Windows 10 "check for update" throws errors

### ISSUE THREAD

**Issue by NickParks** [denysdovhan/learnyoubash#5] opened 2016-02-21 18:15 UTC
Clicking the "Check for update" option seems to throw the error below.

![another error](https://cloud.githubusercontent.com/assets/5506537/13204390/df8aabba-d883-11e5-8b6d-1f6b41613bf9.PNG)

However upon manually executing the command it seems to have worked
![it worked](https://cloud.githubusercontent.com/assets/5506537/13204399/fb3f05e0-d883-11e5-8030-5c6e27e3be9f.PNG)

**Comment by denysdovhan** [comment] 2016-02-21 20:45
I think this is a problem with workshopper-adventure.

**Comment by martinheidegger** [comment] 2016-02-22 01:02
@SirNickParks Would you mind to run `where npm` ?

**Comment by NickParks** [comment] 2016-02-22 01:03
@martinheidegger 

```
$ where npm
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
```

**Comment by martinheidegger** [comment] 2016-02-22 01:06
Okay, thanks. I can confirm its a bug in workshopper-adventure. will continue in https://github.com/workshopper/workshopper-adventure/issues/47

**Comment by denysdovhan** [comment] 2017-12-25 22:24
Duplicate of workshopper/workshopper-adventure#47

**Closed as completed by denysdovhan** 2017-12-25 22:24 UTC
Labels: bug
