### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by neurorishika** [denysdovhan/learnyoubash#52] opened 2017-07-18 05:39 UTC
Following error during install

```
$ sudo npm install -g learnyoubash
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q git://github.com/codeclimate/javascript-test-reporter.git /home/saptarshi/.npm/_cacache/tmp/git-clone-67bd621d
npm ERR! /home/saptarshi/.npm/_cacache/tmp/git-clone-67bd621d/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/saptarshi/.npm/_logs/2017-07-18T05_34_43_194Z-debug.log
```
Ubuntu 16.04 LTS (Unity Desktop Env)
[2017-07-18T05_34_43_194Z-debug.txt](https://github.com/denysdovhan/learnyoubash/files/1154782/2017-07-18T05_34_43_194Z-debug.txt)

**Comment by denysdovhan** [comment] 2017-12-25 22:23
It's not appeared to be related to `learnyoubash`. As you may notice from the log, the problem is with `git clone`.  This should rather be an issue with `npm`, than with this workshopper itself.

I'm going to close this. Feel free to reopen if you have any additional information.

**Closed as completed by denysdovhan** 2017-12-25 22:23 UTC
Labels: question
